### ISSUE TITLE
Issue 1: Users can view the Big-3 Crypto (BTC,ETH, LINK) table and its info

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/Ogma-Crypto#1]
## 💰 Motivation

The user can see the three most popular cryptocurrency's information. These three are the equivalent to S&P500, NADSAQ and DOW. They will be always displayed, because these three are essential information. If these three are down, everything else is down. Again, very similar to the stock market in that regard.

## 📐 Plan

Build three tables through html with css bootstrap, import values through a XMLHttpRequest from the cryptonator api

## 🖼️ Wireframes

![Users can view the Big-3 Crpyto mobile](https://i.imgur.com/M8x8Xna.png)
![Users can view the Big-3 Crpyto Desktop](https://i.imgur.com/mwbvaEs.png)

## ✅ Task List
- [x] Import CSS Bootstrap 
- [x] Add a navbar, accomplish this through bootstrap
- [x] Build three tables in HTML, style them with Bootstrap, and make sure it correlates exactly like the Feature 1 figma (mobile and desktop)
- [x] Add a div[data-view="big-three"] to the HTML tables.
- [x] Build three separate XMLHttpRequest functions, retrieve information pertaining to each table (BTC, ETH, LINK)
- [x] Assign these objects into a variable pertaining the table (Ex. btcObject, ethObject, linkObject)
- [x] Modify the table textContent of each of the table's elements with the variable object you retrieved from the XMLHttpRequest.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
