### ISSUE TITLE
Issue 2: Users can search for a cryptocurrency and get its information in a table format

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/Ogma-Crypto#2]
## 💰 Motivation

The user can create a table for a cryptocurrency and gets its information (price in terms of their target, target, Volume, and change over last hour). This is assuming that the crypto actually exists and is a verified token. 

## 📐 Plan

Build a table through the dom via javascript, build a function that takes the input from the user, and takes its value and does a XMLHttpRequest with it. If the input is valid, the table is appended and its text content is filled from the object that was retrieved.

## 🖼️ Wireframes

![Users can search for a cryptocurrency and get its information in a table format mobile](https://i.imgur.com/R2I8hI6.png)
![Users can search for a cryptocurrency and get its information in a table format Desktop](https://i.imgur.com/OGOGlWl.png)

## ✅ Task List
- [x] Create an anchor tag, add it to the navbar
- [x] Create a new div element on the HTML for the user-generated tables. Set its data-view as "table-form"
- [x] Create an alert message from bootstrap, use their version. Set it hidden.
- [x] Create a form element:
  - [x]  Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
  - [x] Make all inputs of the journal entry form required
  - [x] Implement a submit button
  - [x] implement an overlay
  - [x] Make it appear when the anchor tag made earlier is clicked on  
- [x] Create a data object in data.js
  - [x] have a view property with a string value of 'table form' 
  - [x] take account of user-generated tables and put them in a list. Named data.forms
  - [x] future proof your object and add an editing property, set it to null
  - [x] have a newTableID property with a value of 1
- [x]  Listen for 'submit' events on the table form and:
  - [x]  Put the form's input values into a new object.
  - [x]  Add the nexTableId to the object.
  - [x] increment the nextTableID on the data model
  - [x] unshift the object to the data.forms.
  - [x] call the retrieveUserCrypto function, passing the object as an argument
- [x]  In the retrieveUserCrypto function
  - [x]  A new XMLHttpRequest
  - [x]  retrieve the information from the API by using the objects properties values
  - [x] if the status is not 200, activate the alert that was created earlier and end the function
  - [x] If it is 200, retrieve the object and assign its properties values to variables
  - [x] assign these variables to a new object
  - [x] call the userGeneratedTable function, with an object as an argument
- [x]  In the userGeneratedTable function, select the table holder, call the CreateTableTree function, with the object called as an argument, and prepend it to the table holder.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
