### ISSUE TITLE
Issue 3: Users can save a Crypto-Data-Feed Table

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/Ogma-Crypto#3]
## 💰 Motivation

The users table that got created in the previous feature gets saved.

## 📐 Plan

Implement local storage in order to save the table. The values that get saved are the tableID, input ID and target, the rest of the values get regenerated through XMLHttpRequest. Similar to the Big Three.

## 🖼️ Wireframes

![Users can save a Crypto-Data-Feed Table Mobile](https://i.imgur.com/VEp3sRR.png)
![Users can save a Crypto-Data-Feed Table Desktop](https://i.imgur.com/rKFLW2j.png)

## ✅ Task List
- [x] In data.js, implement local storage
  - [x] Look at your main.js's getDataForUser, take note **when** userObject is being unshifted into data.tables
  - [x] inputInfo is saved to local storage on page reload.
  - [x] Ensure that local-storage is clean.
- [x] Use a loop to grab current values for each user entry in the data model, use those values to create a DOM tree and append it to the page when the 'DOMContentLoaded' event is fired.
- [x] Go in a private browsing session, ensure full functionality, and test local storage extensively.
- [x] Remove any unnecessary CSS styling.
- [x] Remove any errors.

**Comment by vkahlon** [comment]
- [ ] In data.js, implement local storage
  - [ ] Look at your main.js's getDataForUser, take note **when** userObject is being unshifted into data.tables
  - [ ] inputInfo is saved to local storage on page reload.
  - [ ] Ensure that local-storage is clean.
- [ ] Use a loop to grab current values for each user entry in the data model, use those values to create a DOM tree and append it to the page when the 'DOMContentLoaded' event is fired.
- [ ] Go in a private browsing session, ensure full functionality, and test local storage extensively.
- [ ] Remove any unnecessary CSS styling.
- [ ] Remove any errors.
