### ISSUE TITLE
Issue 4: Users can edit or delete a Crypto-Data-Feed Table

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/Ogma-Crypto#4]
## 💰 Motivation

The user can edit their table by modifying the inputs (Crypto ticker and target). If the user wants the table gone, they can delete it.

## 📐 Plan

Utilize the tableID list to keep track what ID is being modified and bubbling to distinguish which table is being selected. A new object gets created when the update button gets selected, and replaces the existing one.

## 🖼️ Wireframes

![Users can edit or delete a Crypto-Data-Feed Table mobile](https://i.imgur.com/KM76ap5.png)
![Users can edit or delete a Crypto-Data-Feed Table Desktop](https://i.imgur.com/MNOR69I.png)

## ✅ Task List
- [x] Update table rendering function to include an edit icon for each rendered entry except big-three.
  - [x] space out the header and the icon evenly
- [x] Ensure that each rendered table is given a data-entry-id attribute indicating which entry it is.
- [x] Listen for clicks on the parent element of all rendered entries.
- [x] Show an entry form if the edit icon was clicked.
  - [x]  Pre-populate the entry form with the clicked entry's values from the object found in the data model.
  - [x] swap submit text with update text
  - [x] include a delete button
- [x] If the edit input is invalid, alert the user.
- [x] Update the table form's submit handler function to conditionally add a new entry object or update the existing one. 
- [x] Update the table form's submit handler function to conditionally add a new entry DOM tree or replace the existing one.
- [x] If the User hits the delete button
  - [x] Show a confirmation modal
  - [x] Hide the modal if the user clicks Cancel.
  - [x] Remove the table from the data model and the entry's DOM tree from the page if the user clicks Delete.
  - [x] Show the table list if the user clicks Delete.
- [x] Optimize your main.js. 
- [x]  Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x]  Test all functionality again in a private browsing session.
