### ISSUE TITLE
Issue 5: Users can compare a crypto in different markets

### ISSUE THREAD

**Issue by vkahlon** [vkahlon/Ogma-Crypto#5]
## 💰 Motivation

The user can compare the value of a cryptocurrency for different vendors

## 📐 Plan

Intake two inputs (Crypto-1 ID and target), builds a table that lays out vendor and their price. User can also edit and delete these tables.

## 🖼️ Wireframes

![Users can compare two cryptos and see differences in its information mobile](https://i.imgur.com/pfTk8dC.png)
![Users can compare two cryptos and see differences in its information Desktop](https://i.imgur.com/OhjCiTY.png)

## ✅ Task List
- [x] Add a new anchor tag to the navbar
- [x] Create a new form
  - [x] Have 2 labels and inputs, (1 ticker, 1 target)
  - [x] have it only appear when the user clicks on the anchor tag
  - [x] have an exit button on the right which takes you back to the homepage
  - [x] have a submit button
  - [x] form is in a modal style
 - [x] when the user hits the submit button on the form
   - [x] grab the input data
   - [x] put the input data into an object, assign them a value
   - [x] call the retrieve market function taking the previously step variable as an argument
 - [x] In the retrieveComparison
   - [x] A new XMLHttpRequest
   - [x] retrieve the information from the API by using the objects properties values
   - [x] if the input is invalid, activate the alert
   - [x] retrieve the object and assign its properties values to variables, including the markets
   - [x]  call the userMarketTable function, with an object as an argument
  - [x] Generate a market table through the DOM, then append it.
  - [x] In data.js, include a new list for marketTables
  - [x] in each reload, have the tables created
- [x] Ensure that each rendered table is given a data-entry-id attribute indicating which entry it is.
- [x] Listen for clicks on the parent element of all rendered entries.
- [x] Show an entry form if the edit icon was clicked.
  - [x]  Pre-populate the entry form with the clicked entry's values from the object found in the data model.
  - [x] swap submit text with update text
  - [x] include a delete button
- [x] If the edit input is invalid, alert the user.
- [x] Update the table form's submit handler function to conditionally add a new entry object or update the existing one. 
- [x] Update the table form's submit handler function to conditionally add a new entry DOM tree or replace the existing one.
- [x] If the User hits the delete button
  - [x] Show a confirmation modal
  - [x] Hide the modal if the user clicks Cancel.
  - [x] Remove the table from the data model and the entry's DOM tree from the page if the user clicks Delete.
  - [x] Show the table list if the user clicks Delete.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
